coreos/scripts

- build_image
- build_library/prod_image_util.sh
This allows us to play with different image bases.
> build_image: add ability to pick different base package

- build_library/disk_layout.json
A brief summary: https://lwn.net/Articles/627232/ ;-)
> disk_layout: switch to ext4 as the default root filesystem.

- build_library/build_image_util.sh
- build_library/prod_image_util.sh
Related https://github.com/coreos/coreos-overlay/pull/1055
> build_library: add extract_docs()

- oem/ami/publish_ami.sh
This was not a valid json document before. Actually make this an object.
> oem/ami: fix ami_all.json

- update_chroot
Better improved multiple repo support handling code. Replaces my prior pull requests coreos/scripts#370 and coreos/chromite#18
> Auto symlink repo configs

- build_library/toolchain_util.sh
Adds basic support for arm64 platforms.  Please consider.
-Geoff
> Add basic support for arm64 

- build_packages
- setup_board
Two minor cleanups for scripts I had accumulated.
> scripts: Minor cleanups

- build_library/vm_image_util.sh
Lets us avoid larger data transfers when importing images.
> vm_image_util: add support for VMDK images for EC2 AMIs

- oem/azure/replicate-image.sh
This extra metadata is needed by Azure's new portal.
> oem/azure: add more metadata to images

- ROADMAP.md
Adding developers to this project has taken longer than expected.
> ROADMAP: bump completion of arm64 to next quarter

- oem/ami/test_ami.sh
> oem/ami: up SSH timeout to 10 minutes

- build_library/disk_util
- build_library/prod_image_util.sh
Branch adds option to disk_util for dumping verity hashes in the build directory
> dm-verity hash output

- bootstrap_sdk
- sdk_lib/enter_chroot.sh
- sdk_lib/make_chroot.sh
- setup_board
- update_chroot
- update_distfiles
This reduces some of the magic in make_chroot.sh, making it easier to replace.
> Simplify SDK setup

- bootstrap_sdk
- sdk_lib/make_chroot.sh
catalyst tries to run sed on it after the rm step :(
> bootstrap_sdk: do not remove make.conf

- build_library/vm_image_util.sh
Adding packet to the list of img and oem types.
> Adding packet to the list of img and oem types.

- ROADMAP.md
> ROADMAP: add plans for ci integration

- contrib/create-basic-configdrive
> Fixed outdated virtualbox etcd2 script

- build_library/qemu_template.sh
- build_library/vm_image_util.sh
Enables the creation of the qemu launch script for arm64 images.
> Add arm64 qemu image support

- common.sh
Broken in 0b6acf86 when we started selectively reading version.txt
> common: set properly COREOS_SDK_VERSION

- oem/ami/regions.sh
Fixes https://github.com/coreos/bugs/issues/1100
> ami: add new Soeul region

- build_image
- build_library/build_image_util.sh
This is a resubmit of https://github.com/coreos/scripts/pull/522.
Rebased to latest.
> build_image: Fix image type conditional

- oem/ami/prod.sh
> oem/ami: fix call to update_json.sh

- oem/ami/regions.sh
> oem/ami: add aki for ap-south-1

- build_library/build_image_util.sh
- build_library/prod_image_util.sh
- core_sign_update
- offline_signing/download.sh
- offline_signing/sign.sh
This doesn't do anything to enable kernel signing or verity, just adds the kernel to the update payload.
> Include kernel in update payloads

- oem/openstack/glance_load.sh
Add a board argument to allow arm64 downloads.
/cc @brianredbeard
> glance_load: Add board argument

- oem/ami/regions.sh
Fixes https://github.com/coreos/bugs/issues/1623.
> oem/ami: add us-east-2

- oem/ami/publish_ami.sh
This is needed so that users can copy the public AMIs into their own
accounts.
> oem/ami: make snapshots public

- build_library/set_lsb_release
/cc @philips @robszumski @meghanschofield
> set_lsb_release: update name and color

- oem/ami/regions.sh
Fixes https://github.com/coreos/bugs/issues/1733.
> oem/ami: add eu-west-2 and ca-central-1 regions

- build_library/build_image_util.sh
- build_library/modify_image_util.sh
- image_inject_bootchain
- image_set_group
Add script to replace the unsigned kernel, EFI GRUB, and shim in an image's EFI System Partition with (externally-produced) signed ones.
> Add script to inject kernel/GRUB/shim

- build_library/vm_image_util.sh
For coreos/bugs#359.
/cc @bgilbert
> Build the vmware_raw format for stable

- build_library/toolchain_util.sh
- build_library/vm_image_util.sh
> Fixes for beta

- build_library/catalyst.sh
- update_chroot
This is part of coreos/portage-stable#533.
> Update Perl to fix the last GLSA

- bootstrap_sdk
- build_toolchains
This is a continuation of #660.
> Upload package signatures from the bootstrap process

- build_library/set_lsb_release
> Use consistent URLs in the distro files (beta)

- build_library/set_lsb_release
> Use consistent URLs in the distro files (stable)

- build_image
- build_library/vm_image_util.sh
- image_to_vm.sh
qemu makes no sense on that platform.
> image_to_vm: Default to qemu_uefi on ARM

- build_image
- build_library/build_image_util.sh
- build_packages
- build_torcx_store
Part of coreos/coreos-overlay#2567.
> Populate the torcx vendor store in OS images

- chromeos-common.sh
The last user was in 82e2461ddf816a5a534eb870e47bb09314f71fbb. Relevant context in e84f922ba5430851fe534273c4947ebcc7e8c8e7.
> chromeos-common.sh: Drop symlink

- core_sign_update
- offline_signing/sign.sh
Backport #710 and #712 to stable
> Use signing cards

- offline_signing/transfer.sh
Also parallelize download of artifacts for signing, mostly to stop gsutil from complaining that we didn't.
> offline_signing: Mechanize more roller interactions

- build_library/build_image_util.sh
- build_library/torcx_manifest.sh
> Include on-disk torcx source packages in the package list

- build_library/build_image_util.sh
- build_library/torcx_manifest.sh
> Add torcx source packages to the package list in alpha

- build_library/torcx_manifest.sh
> build_library: Filter out null paths in torcx manifests

- build_library/vm_image_util.sh
- build_torcx_store
> Add Docker 17.06 to the image for 1520

- build_torcx_store
Backports #759
Depends on coreos/coreos-overlay#2799
> Update Docker to 17.09 and add 17.03 in beta

- build_library/disk_util
It hasn't been used since 5bfa0c8d2013d075b72907d0a9552877b66c542c.
> disk_util: drop support for syslinux partition feature

- build_torcx_store
Part of coreos/coreos-overlay#2914
> build_torcx_store: Update the default Docker to 17.11

- build_library/test_image_content.sh
- build_library/toolchain_util.sh
- update_chroot
Part of coreos/portage-stable#557.
> Upgrade to GCC 6.4.0

- build_library/set_lsb_release
> set_lsb_release: update codename for 1675

- build_library/catalyst.sh
> Disable ccache for catalyst in alpha

- build_library/catalyst.sh
> Disable ccache for catalyst in beta

- build_library/build_image_util.sh
Hopefully will work around https://github.com/coreos/bugs/issues/2284
> build_image: run grub_install.sh twice

- offline_signing/transfer.sh
> transfer.sh: use update-percent in updateservicectl calls

- build_torcx_store
Part of coreos/coreos-overlay#3230
> Upgrade Docker to 18.05

- signing/transfer.sh
We're no longer publishing arm64-usr releases.
Untested.
> transfer.sh: Drop support for boards other than amd64-usr

- build_library/catalyst_toolchains.sh
- build_library/toolchain_util.sh
- build_library/vm_image_util.sh
- build_torcx_store
- setup_board
Part of coreos/coreos-overlay#3311
(This does work with arm64, despite it no longer being built.)
> Work with new portage sysroot behavior

- signing/sign.sh
Update to use the actual key names and IPs.
> signing/sign.sh: update to use correct keys/ips

- build_library/catalyst_default_stage4.sh
This will allow updating its SDK version as it promotes through the channels.
> Backport the SDK Python fix to alpha

- build_library/toolchain_util.sh
- jenkins/sdk.sh
Part of coreos/portage-stable#690
> update_chroot: Allow upgrading glibc and binutils

- update_chroot
Part of coreos/portage-stable#699
> update_chroot: Work around dead cargo file conflicts

- build_library/catalyst.sh
This reverts commit 373d5a814ba7b4ecba181ad37b8b4c8b98bd0402.
> Revert "catalyst: Temporarily disable update_seed again"

- build_library/disk_util
Backport https://github.com/coreos/scripts/pull/864.
> disk_util: Add -I for mkfs.vfat for 2023

- build_library/catalyst.sh
Part of coreos/portage-stable#726
> catalyst: Temporarily disable update_seed again

- jenkins/sdk.sh
- jenkins/toolchains.sh
It's already built into the SDK since coreos/coreos-overlay#3683.
> jenkins: Stop trying to install catalyst

- setup_board
This reverts commit 3d60305f24aac79dade4e7c20a3a8d395621422a.
> Revert "setup_board: add workaround for binutils issue"

- build_library/disk_util
Retry losetup if it fails, up to 5 times with 5 seconds between retries.
> build_library/disk_util: work around losetup bug

- build_library/disk_util
Retry losetup if it fails, up to 5 times with 5 seconds between retries.
> build_library/disk_util: work around losetup bug (beta)

- build_library/disk_util
Retry losetup if it fails, up to 5 times with 5 seconds between retries.
> build_library/disk_util: work around losetup bug (alpha)
