build_library/catalyst.sh
Disable ccache as it is causing issues in other builds so disable it
everywhere to be safe. Disable the autoresume feature because our build
process doesn't actually make use of it.
=> catalyst: disable ccache and autoresume

build_library/toolchain_util.sh
Fix parsing the following output:
[ebuild  N    ] dev-libs/gmp-5.1.3-r1 to /usr/x86_64-cros-linux-gnu/
[ebuild     UD] sys-libs/timezone-data-2013d [2014i-r1] to /usr/x86_64-cros-linux-gnu/
The previous regex did not account for upgrades and got confused by the
`[2014i-r1]` listing and goobbled up too much of the string. I am not
sure *why* portage is reporting an upgrade when --emptytree is also used
but there it is. Match all not-] characters instead.
=> toolchain_util: fix parsing emerge --pretend output

build_library/disk_util
This change changes the default 'bytes-per-inode' ration from 16K to 4K,
the block size. To prevent this from wasting too much space change the
inode size from the default 256 to the minimum size, 128. Larger inodes
are used to store extended attributes more efficiently but since we do
not use SELinux the majority of files do not have security attributes.
These defaults may be modified via the new `bytes_per_inode` and
`inode_size` options.
Fixes https://github.com/coreos/bugs/issues/264
=> disk_util: allocate the maximum number of usable inodes

build_library/vm_image_util.sh
=> use correct group name in production images with no writeable /etc

build_packages
Sorry, this is just getting bad. We need to switch to initializing the
board root stage3 style, similar to how the SDK or most any
semi-complicated Gentoo install starts. Breaking loops while merging
into a clean root is just too complicated.
On what this does: util-linux now has a udev *and* a systemd use flag.
Since we use systemd they both are effectively the same and pull in the
systemd package. This adds support for disabling both flags during the
loop breaking procedure.
=> build_packages: add support breaking loops with multiple use flags

build_library/build_image_util.sh, build_library/dev_image_util.sh, build_library/prod_image_util.sh
There isn't a sane way for users to know the licenses of individual
packages in CoreOS images in built images. The information is hidden
away back in the original ebuilds. This extends our existing package
list with a new file that also includes licenses:
```
app-admin/flannel-0.3.0-r3::coreos Apache-2.0
app-admin/fleet-0.9.1::coreos Apache-2.0
app-admin/locksmith-0.2.3::coreos Apache-2.0
app-admin/sdnotify-proxy-0.1.0::coreos Apache-2.0
app-admin/sudo-1.8.10_p2::portage-stable ISC BSD
app-admin/toolbox-0.0.0-r4::coreos Apache-2.0
app-arch/bzip2-1.0.6-r6::portage-stable BZIP2
app-arch/gzip-1.5::portage-stable GPL-3
app-arch/tar-1.27.1-r2::portage-stable GPL-3+
...
```
=> build_image_util: generate package license list for each image

build_library/disk_util
Previously fsck output was suppressed to reduce the amount of noise in
build logs on the assumption that fsck really shouldn't have a reason to
fail. The filesystem is freshly created after all. However some users
have reported that fsck is failing but without error messages we don't
know why.
=> disk_util: include fsck output during resize operation

oem/ami/test_ami.sh
The v1 API has been removed, so use v2 instead. The 10-second sleep was
added because the fleet tests were failing without it. My guess is that
etcd needed some time to warm up before we flooded it with requests.
=> oem/ami: update tests for etcd2

build_library/catalyst_toolchains.sh, build_library/toolchain_util.sh, setup_board
Replaces https://github.com/coreos/scripts/pull/388, pruning down the diff a little.
In addition to (hopefully) fixing true cross-architecture builds this resolves an issue caused by the recent mpc upgrade. Since without this CHOST==CBUILD cross-compiling logic wasn't properly engaged and the two-phase gcc build kicked in, linking against some things under `/build/$BOARD` but then failing to run because the host chroot had a different mpc library.
=> Fixes for cross compiling

build_library/catalyst.sh, build_library/catalyst_toolchains.sh, build_library/toolchain_util.sh, update_chroot
This is required for the eventual removal of `$PORTDIR` and
`$PORTDIR_OVERLAY` and ensures toolchain rebuilds/updates with
`./build_packages --nousepkg` don't erroniously try to use ebuilds from
`/usr/portage` inside of the SDK.
In order to fix up the build_toolchains script the crossdev overlay
needs to be setup properly, previously only setup_board did it.
Overall silences a lot of warnings and fixes an issue with crossdev:
/usr/bin/emerge-wrapper: line 48: /eclass/toolchain-funcs.eclass: No such file or directory
/usr/bin/emerge-wrapper: line 49: tc-arch: command not found
=> toolchain_util: include repos.conf in bootstrap build environments

setup_board
For some reason package moves are not handled automatically in the board
build roots. Add explicit calls to emaint to update cached binary
packages, installed packages, and the world file.
=> setup_board: explicitly perform all package moves

oem/ami/import.sh, oem/ami/master.sh, oem/ami/prod.sh, oem/ami/user.sh
This script uses the EC2 volume import tools instead of attaching and
writing to an EBS volume. This mechanism will be useful for creating
AMIs in isolated EC2 regions and can be run from any host with API
access and the EC2 tools.
TODO: Allow region to be specified and automatically create region-local
S3 buckets as needed. This version hard codes a bucket only usable by
our dev AWS account, not prod. Later on: move to a more compact disk
format like VMDK.
=> oem/ami: add new import script, replaces build_ebs_on_ec2.sh

oem/ami/import.sh, oem/ami/make_bucket.sh
The intent is to export the bucket and optionally the zone in the
environment alone with the AWS auth credentials.
=> oem/ami: make import zone and bucket conferable

oem/ami/master.sh, oem/ami/prod-publish.sh, oem/ami/prod.sh, oem/ami/user.sh
The ami builder host now has a proper checkout of the scripts repo.
=> oem/ami: update path to ami scripts directory

build_library/build_image_util.sh, build_library/grub.cfg, build_library/grub_install.sh
grub needs shim in order to verify kernels, and we need to rework our image format a little to enable the dm-verity work. This gets us to a fully trusted boot chain in the qemu-uefi-secure target.
=> Add support for signed kernels

oem/ami/copy_ami.sh, oem/ami/import.sh, oem/ami/prod-publish.sh, oem/ami/prod.sh, oem/ami/publish_ami.sh, oem/ami/regions.sh, oem/ami/test_ami.sh
A few general changes:
- Use https for EC2 endpoint URLs
- Remove parallelism from prod-publish, was launching enough Java
processes at once to trigger OOM :(
- Only share snapshots with Amazon in us-east-1: only needed for
marketplace listing and marketplace only uses us-east-1.
=> oem/ami: add support for publishing AMIs in us-gov-west-1

build_image, build_library/dev_image_util.sh
- "./build_image prod" already has the ability to specify which package will specify all the packages that should be pulled in and built into an image by specifying a package name using the --base_pkg command line flag. This creates an equivalent option for "./build_image dev" creating a --base_dev_pkg flag that passes a package name into the create_dev_img() function in dev_image_util.sh the same way that --base_pkg is passed into create_prod_image() inside prod_image_util.sh.
=> Enhanced dev_image_util with equivalent to --base_pkg

LICENSE, README.md, ROADMAP.md
This doc covers CoreOS as a whole and a few details that don't really
fit anywhere else. Individual projects maintain their own roadmaps.
Update LICENSE and add a README as general housekeeping.
=> ROADMAP: add initial overall CoreOS roadmap document

build_library/grub.cfg, build_library/grub_install.sh
We don't want untrusted configuration to be read if we're in Secure Boot
mode, so skip the OEM config when Secure Boot is enabled and in User Mode.
=> Don't read OEM config data if Secure Boot is enabled

build_library/template_vmware.ovf, build_library/vm_image_util.sh
=> image_to_vm: fix OVF filename

core_promote
Description will now look like:
CoreOS, CoreOS alpha, 695.0.0, amd64-usr published on 2015-05-28
=> core_promote: update to new standard GCE image description format

contrib/create-basic-configdrive
This extends in scripts/contrib/create-basic-configdrive the regexp matching ssh rsa and dss keys to ed25519 keys so modern crypto is supported.
=> recognize ssh ed25519 keys

build_packages
Previously we attempted to speed up the first build of a board by
pulling in binary packages regardless of their use flags, assuming that
if the package was already built the loop would not be an issue. Usually
this was true but not always. Now things like util-linux will always get
compiled when setting up a board for the first time but at least it
won't be as likely to fail.
=> build_packages: always rebuild when breaking dependency cycles

bootstrap_sdk, build_library/release_util.sh
SDK tarballs have a .DIGESTS file but it is created by catalyst instead
of the upload_image function. In order to support plain GPG signing but
not avoid re-generating .DIGESTS we need to move that code out of
upload_image to a new function. upload_files shouldn't do it itself
because it is also used for portage binary packages which shouldn't be
signed (there is no point, nothing would verify the signatures).
=> bootstrap_sdk: add support for directly GPG signing SDK tarballs

contrib/create-basic-configdrive
This check helps to avoid exit the script with the message indicating
success even though the mkisofs is missing and an image has not been created.
=> Add check for mkisofs

oem/ami/import.sh
turns out this is a really non-trivial speedup, so this turned into low hanging fruit that fell off the tree pretty quickly, figured I could share the speedup with the rest of the CoreOS world. since `ixgbevf` is already loaded on coreos, all we need to do is enable `sriov` support on the AMI itself [1]. I believe this is all we need to do, however, like most amazon docs, it's not entirely clear and there are 18 ways to skin the cat ;). per [2] this is the recommended method on 'instance-backed' but the recommended way on 'ebs-backed' is to run an instance, stop it and modify it; I believe they recommend this way in order to add the kernel module, which CoreOS already has. I have an inkling that registering the ami with the `sriov` flag will just work [on instance backed and ebs backed], …
=> hvm ami enable sriov on image

build_library/build_image_util.sh
Create an selinux policy at image build time - despite the -i flag, this
won't attempt to install it into the running kernel.
=> Build selinux policy

build_image, build_library/build_image_util.sh, build_library/grub.cfg, build_library/grub_install.sh, build_library/prod_image_util.sh
This adds dm-verity support to prod builds under the flag `--enable_verity`. It currently has an issue with preventing the OEM disk from mounting.
=> dm-verity build support

build_packages
The --rebuild-if-unbuilt emerge option will recompile packages if any
build-time dependencies changed. This can be a useful safety to make
sure applications get re-linked and so forth. However recent versions of
portage have grown better defaults for choosing when to rebuild so lets
turn the build_packages flag around and leave emerge to do its default
behavior and see if that is sufficiently safe.
=> build_packages: be less aggressive about rebuilding packages

build_library/disk_util
Depends on https://github.com/coreos/seismograph/pull/32.
=> disk_util: use the dummy disk UUID

build_library/grub_install.sh
Useful for repairing the MBR without needing GRUB's tools.
=> grub_install: stash an exact copy of the MBR boot code.

build_packages, update_chroot
Before attempting to do @preserved-rebuild to fix linked against old
libraries remove any packages that no longer have corresponding ebuilds,
making them impossible to rebuild. This uses `--depclean`'s secondary
meaning: `--unmerge` but only remove packages without dependencies.
=> update_chroot/build_packages: remove obsolete packages

setup_board
These are properly detected now.
=> setup_board: remove old kernel vars

build_library/build_image_util.sh, build_library/dev_image_util.sh, build_library/prod_image_util.sh
ldconfig does not work for non-native arches.  Create a new
build_image routine run_ldconfig that uses qemu user emulation
to run the board ldconfig on the board rootfs when the board and
SDK arches are different.
See: http://code.google.com/p/chromium/issues/detail?id=378377
Prior to calling run_ldconfig the board rootfs must have ldconfig
installed.  To arrange this move the call of run_ldconfig to after
the base package install.
Fixes build_image errors like these when building for arm64:
/sbin/ldconfig: /lib64/libXXX is for unknown machine 183.
Depends on https://github.com/coreos/coreos-overlay/pull/1424
@marineam I'm still testing this, but wanted to get it out for your comments before I put too much into it.
/cc @andrejro
=> scripts: Run ldconfig in qemu

build_library/build_image_util.sh
Failing to explicitly set the selinux policy store to operate on may
result in semodule installing the policy in an incorrect location. Pass
it on the command line in order to avoid this.
=> Ensure that selinux policy is installed in correct location

build_library/catalyst.sh
Now that ccache is turned on by default in the profile portage complains
a lot if ccache isn't actually installed, sleeping 5 seconds for each
error message. Since pkgcache is in use ccache isn't going to make that
much of a difference but getting rid of those 5 second sleeps will. :)
=> catalyst: re-enable ccache

ROADMAP.md
We have de-emphasized strudel and are concentrating on testing/release/ignition for now. Remove it for the roadmap.
cc @pbx0
=> ROADMAP: remove strudel

build_library/grub.cfg
In order to boot properly we need `rootflags=rw mount.usrflags=ro` on
the command line. These have been build into the kernel directly but for
arm64 builds the built in options seem to be ignored.
=> grub: move standard kernel options to grub

contrib/create-basic-configdrive
The DEFAULT_ETCD_DISCOVERY parameter had a typo in the scheme part of the URI. It missed a colon after https.
This lead to failure on the discovery of the cluster when the token based discovery was used as the https://discovery.etcd.io could not be reached during the boot/configuration process.
=> Fixed typo on URI for DEFAULT_ETCD_DISCOVERY.

build_library/grub.cfg
coreos.first_boot=1 will no longer trigger disk-guid randomization, so
manual ignition triggers in diskless/pxe scenarios may succeed.  Instead
we explicitly request the randomization when first_boot=1 was added by
grub finding the 00000000-0000-0000-0000-000000000001 disk-guid.
=> grub: add and set coreos.randomize_disk_guid kernel param

build_library/grub.cfg
The console often contains very useful information in the event of a
hard crash, in such situations there's no ability to unblank the console
via keypress because the kernel won't handle the interrupt.
Since CoreOS is a server/cluster operating system, there won't generally
be monitors connected benefitting from a blanked console.  Disabling the
blanking altogether allows the frame buffer contents to always be
visible, even when the kernel can't handle keypresses.
=> grub: disable console blanking

common.sh
This call to a python script is merely used to get a static list of
environment variables that happens to be defined in that repo.
=> common: don't get env list from chromite

prune_images
This may include recent failures or builds derrived from latest, such as
those made by image_set_group.
=> prune_images: keep newer-than-latest builds

common.sh, sdk_lib/enter_chroot.sh
- Support arbitrary $GNUPGHOME values, avoiding conflicts in $HOME for jenkins builders.
- Allow setting COREOS_BUILD_ID in the environment so it can be mapped directly to a jenkins job instead of using the date.
=> Updates for jenkins builds

sdk_lib/enter_chroot.sh
The path of $GNUPGHOME outside the chroot may not really make sense
inside the chroot. Although that's probably not a big deal there's no
need to keep the outside value. Instead just bind it to the usual spot.
=> enter_chroot: always bind $GNUPGHOME to the default path

sdk_lib/enter_chroot.sh
Commit 09851b84 didn't do a recursive bind by mistake, so if the host
system has anything mounted under the chroot directory for some reason
the bind would hide those mounts. Recursive ensures existing mounts
remain exposed as they did before.
=> enter_chroot: fix chroot root bind command

build_library/release_util.sh
This simplifies the code a little and allows BOTO_PATH or BOTO_CONFIG to
be set in the environment. Now configs may be in arbitrary locations.
=> release_util: use BOTO_PATH instead of searching for .boto

core_date
Compute coreos version for a date or the date of a coreos version.
Arguments are passed to `date` except for `-v` which takes an optional
version value and converts it to a date. `-v` must be the first arg.
$ ./core_date
945
$ ./core_date -d wed
947
$ ./core_date -v
Fri Jan 29 00:00:00 UTC 2016
$ ./core_date -v +%D
01/29/16
$ ./core_date -v 1000
Sun Mar 27 00:00:00 UTC 2016
$ ./core_date -v 1000 +%D
03/27/16
=> core_date: dumb little script so I can stop doing math

build_packages, setup_board, update_chroot
This maps to the emerge flag of the same name. Prevents building anything from source and is a quicker way to bootstrap the board for the first time.
=> New build script flag --usepkgonly

setup_board
PR https://github.com/coreos/scripts/pull/478 added the pieces to allow us to build the grub modules for arm64 boards, but the user still needed to run emerge by hand to build them.
This PR automates that by running the emerge of the SDK sys-boot/grub again at the very end of setup_board to pick up any config changes that were made within setup_board.  This late emerge is not specific to arm64 and will build grub modules for any architecture that is different from the host.
=> setup_board: Build grub platform modules

build_library/vm_image_util.sh
Most vm images have an expanded root partiton to make them practical to
use as-is. Some deployments may not want such a large root, putting most
storage on other volumes.
/cc @rcreasey
=> vm_image_util: add a small openstack image for wedging into tiny places

build_image, build_library/board_options.sh, build_library/build_image_util.sh, build_library/prod_image_util.sh, build_packages, setup_board, update_chroot
A step towards running builds in parallel *and* efficiently, this allows build_image to download binary packages itself instead of depending on build_packages to do it.
=> Support using build_image without running build_packages first

core_promote
This cleans out some old crud:
```
Removing gs://alpha.release.core-os.net/amd64-usr/current/au-generator.zip
Removing gs://alpha.release.core-os.net/amd64-usr/current/au-generator.zip.DIGESTS.asc
Removing gs://alpha.release.core-os.net/amd64-usr/current/au-generator.zip.DIGESTS.sig
Removing gs://alpha.release.core-os.net/amd64-usr/current/au-generator.zip.DIGESTS
Removing gs://alpha.release.core-os.net/amd64-usr/current/au-generator.zip.sig
Removing gs://alpha.release.core-os.net/amd64-usr/current/coreos_developer_image.bin.bz2
Removing gs://alpha.release.core-os.net/amd64-usr/current/coreos_developer_image.bin.bz2.DIGESTS.asc
Removing gs://alpha.release.core-os.net/amd64-usr/current/coreos_developer_image.bin.bz2.DIGESTS
Removing …
```
=> core_promote: switch from gsutil cp to rsync

contrib/create-basic-configdrive
create-coreos-vdi fails to properly quote paths containing spaces, which may result in a failing execution of mkisofs. Due to missing error handling on this, create-coreos-vdi would also claim "Success" while the mkisofs execution actually failed.
This patch does add the missing quotes around "CONFIGDRIVE_FILE" (and around WORKDIR, just for completeness). It also adds a simple error message on a failed mkisofs operation.
=> enable spaces in path names, add minimum error handling

build_library/prod_image_util.sh
profile is already set up to source /usr/share/baselayout/profile.env
but it never has because I forgot to add this line during the migration
to amd64-usr images. Sure took us a while to notice that one... :(
=> prod_image_util: move profile.env to /usr

core_promote
The build bucket should now be writable anyone performing releases,
allowing us to ensure that the original build and public buckets are
exactly in sync.
=> core_promote: upload gce image name to private build bucket

build_library/build_image_util.sh, build_library/check_root, build_library/test_image_content.sh
Following up from https://github.com/coreos/scripts/pull/505.
```
INFO    build_image: Checking /mnt/host/source/src/build/images/amd64-usr/developer-983.0.0+2016-03-14-1832-a1/rootfs
/usr/libexec/git-core/git-contacts: /usr/bin/perl does not exist
/usr/libexec/selinux/semanage_migrate_store: /usr/bin/python does not exist
/usr/sbin/nfsiostat: /usr/bin/python does not exist
/usr/sbin/ebtables-save: /usr/bin/perl does not exist
/usr/bin/glib-mkenums: /usr/bin/perl does not exist
/usr/bin/import-tars: /usr/bin/perl does not exist
/usr/bin/diff-highlight: /usr/bin/perl does not exist
/usr/bin/mtrace: /usr/bin/perl does not exist
/usr/share/rsync/logfilter: /usr/bin/perl does not exist
/usr/share/rsync/files-to-excludes: /usr/bin/perl does not exist
/usr/share/rsync/file-attr-restore: …
```
=> check_root: add test for missing interpreters

oem/ami/copy_ami.sh
The EC2 builder doesn't have enough resources to run all of these in parallel.
Instead, copy the PV images and then copy the HVM images.
Supersedes https://github.com/coreos/scripts/pull/509.
=> oem/ami: reduce parallelism

build_library/build_image_util.sh, build_library/dev_image_util.sh, build_library/generate_grub_hashes.py, build_library/generate_kernel_hash.sh, build_library/prod_image_util.sh
We need to ship some PCR measurements alongside images in order to make it
easier for admins to provide an appropriate policy. Add some tooling to
generate the appropriate hashes during build, pack those into a zip file
and upload it.
=> Add support for generating PCR configuration at image build time

setup_board
See https://github.com/coreos/coreos-overlay/pull/1883
Builds should be usring /usr/bin/$CHOST-pkg-config instead.
=> setup_board: remove bad pkg-config wrapper

build_library/prod_image_util.sh
A bunch of packages install PAM configuration fragments in /etc. Rather than modify
them all to install into /usr/lib, just move the entire directory at image build
time.
=> Move PAM configuration to /usr at build time

build_library/prod_image_util.sh
in arm64-usr, lib is not yet a symlink to arm64, so trying to access
tmpfiles.d in lib64 will not work.
=> build_library: use lib for tmpfiles rather than lib64

build_image, build_library/disk_layout.json, image_to_vm.sh
devel images contain significantly more code and we're overflowing the
filesystem. Increase this, but only for devel images.
=> Increase the size of /usr on devel images

core_roller_upload
The google domain name is still used for downloads, that will be
switched as soon as the appropriate certificates are set up.
=> core_roller_upload: use new update storage bucket

build_image
Our current scheme injects the verity hash into a free spot in x86
kernel images. This is a bad thing to try on other types ;-)
Smaller alternative to https://github.com/coreos/scripts/pull/521 and https://github.com/coreos/scripts/pull/522
=> build_image: disable verity on arm64

build_library/prod_image_util.sh
arm64-usr doesn't have update_engine yet so this isn't valid.
=> prod_image_util: do not check update keys on arm64

build_library/catalyst.sh, build_library/dev_image_util.sh, update_chroot
Instead of patching portage to support the `disabled` flag now we just
patch it to leave the `[gentoo]` section out of the default repos.conf.
Follow up to https://github.com/coreos/coreos-overlay/commit/585275b268da9f549d93c7c37744dcda3411cca2
=> *: drop obsolete gentoo repo reference

contrib/create-basic-configdrive
Debian (and possibly other distros) no longer ship mkisofs in favor of genisoimage. This MR adds genisoimage support to `contrib/create-basic-configdrive` script.
Thank you, ciao
=> add support for genisoimage

build_library/catalyst.sh, build_library/dev_image_util.sh, update_chroot
Reverts coreos/scripts#538
Not everyone has flushed older versions of portage out of their systems yet. Keep these compatibility configs for a bit longer.
=> Revert "*: drop obsolete gentoo repo reference"

build_library/set_lsb_release
update_engine and CoreUpdate aren't quite ready, use an alternate id so
we can continue testing but not mistakenly serve amd64 updates to arm64.
=> set_lsb_release: use an alternate app id for arm64

oem/ami/import.sh, oem/azure/publish.sh
tmpfs shouldn't be used for large images like this. Inflate the archives
on disk instead.
=> oem: inflate images into /var/tmp

sdk_lib/enter_chroot.sh
COREOS_BUILD_ID is set to a default value in common.sh if unset in the
environment. When entering the chroot this default value should not then
get promoted into the environment. Doing so causes catalyst to re-use
stale builds and multiple build_image runs to conflict with each other.
=> enter_chroot: do not export variables that weren't previously exported

build_library/prod_image_util.sh
The baselayout package now creates and installs /usr/lib/pam.d, causing
mv to fail. Move the contents instead which is happy with both versions.
=> prod_image_util: move pam.d contents, not the directory

build_library/toolchain_util.sh, common.sh
The one-liner `[[ -z ${PIPESTATUS[*]#0} ]]` no longer works because the
expansion still includes spaces even if all the values are zero. Somehow
that didn't matter in bash 4.2 but it does mater in 4.3 to be consistent
with the general behavior of variables in [[ tests.
=> *: Fix PIPESTATUS checks for bash 4.3

oem/openstack/glance_load.sh
The OpenStack client `glance` option `--is-public true` is limited to Image API version 1, and so doesn't work with versions of the glance client where version 2 is the default.
`python-glanceclient` 1.0.0 was the first to do so, and was released Sep 2015, so most new users of this script will need this fix.
=> Glance image API v1 must now be explicitly specified by the client

kernel_menuconfig
depends on coreos/coreos-overlay#2005
=> kernel_menuconfig: fix name of kernel package for split scheme

build_packages
When the --usepkgonly flag was added in d327840ce this step got wrapped
in an inverted test. It should normally be enabled.
=> build_packages: fix @preserved-rebuild

oem/ami/prod.sh, oem/ami/update_json.sh
Since this writes to private storage there isn't any need to wait until
the images are public to do this. Now the final publish step only
changes permissions on the AMIs and nothing more.
=> oem/ami: write ami index files to storage after copy

rebuild_packages
This is a bit of a hack, I would like something a little more
intelligent that checks for applicable metadata changes, not just any
old change in the ebuild text. That will require a bit more work/thought
and this should at least be sufficient to catch the current problems.
The issue comes down to how emerge's --usepkgonly mode works. Normally
KEYWORDS and (R)DEPEND metadata in ebuilds is used to figure out what to
install. If that metadata in the installed or binary packages is is out
of date things generally work out anyway. However when --usepkgonly is
enabled (such as in build_image) the ebuild metadata is ignored, using
only the installed and binary package metadata. Unfortunately it may be
out of date, allowing build_image to fail or otherwise behave
differently from build_packages. …
=> rebuild_packages: new script to catch all ebuild modifications

build_library/grub.cfg, build_library/grub_install.sh
If the gptprio.next command fails to give us something to boot we
shouldn't try! In order to diagnose why the failure happened halt
immediately so the user can see the error message.
For https://github.com/coreos/bugs/issues/1471
=> grub: abort boot if gptprio fails

kernel_menuconfig
Handling configuration changes across multiple architectures is difficult.
Let's just generate a diff in the config and then apply that to the arch or
common config manually.
=> menuconfig: Handle shared architecture configuration

build_library/catalyst.sh
workaround for bootstrap_sdk on an Ubuntu host where /dev/shm is a
symlink to /run/shm. Since we mount the hosts /dev (for losetup) this
interferes with building python 2.7. The workaround is to disable the
/dev/shm during python builds. A longer term fix would be to not mount
the hosts /dev. Thanks for marineam for suggesting the fix on IRC.
=> catalyst: workaround for bootstrap_sdk on Ubuntu

tag_release
Without this, repo will sometimes empty the contents of manifest.xml.
=> tag_release: operate on copy of manifest.xml

build_library/grub.cfg
On HVM instances, tty0 is actually a graphical interface. Since the
interface exposed is non-interactive, it's not possible to scroll
through the logs, which results in lots of missing information. Setting
the console to ttyS0, on the other hand, sends the output to the system
log.
PV instances don't have this issue since they are xen-based and use
hvc0.
=> grub: rename oem_id variable

build_library/dev_image_util.sh
Broken by 1092afd which missed that dev images and containers were also
uploading pcr data despite it not really being applicable to those.
=> build_image: dev images/containers no longer have pcr data

build_image, build_library/build_image_util.sh
Consolidates two very similar flags into one and fix an issue where
verity could get enabled in the GRUB config when rootfs verification was
turned off (e.g. on arm64 which cannot use verity yet).
=> build_image: always enable verity when /usr is read-only

build_library/build_image_util.sh, build_library/dev_image_util.sh, build_library/prod_image_util.sh
Depends on https://github.com/coreos/coreos-overlay/pull/2213
Fixes https://github.com/coreos/bugs/issues/112
I'm not sure if it is truely required to run the target's localedef or if the format is independent enough to just use the hosts. To play it safe I'm using the target's similar to how we handle ldconfig.
=> build_image: generate C.UTF-8 locale

build_image, build_library/build_image_util.sh, build_library/generate_grub_hashes.py
The Xen loader in GRUB never received support for our hacky scheme of
adding the verity hash to the kernel cmdline. Disable till that's fixed.
Partially reverts 2016567 and 533b1b9.
Bug https://github.com/coreos/bugs/issues/1600
=> build_image: disable verity again

build_image, build_library/build_image_util.sh, build_library/generate_grub_hashes.py
The Xen loader in GRUB never received support for our hacky scheme of
adding the verity hash to the kernel cmdline. Disable till that's fixed.
Partially reverts 2016567 and 533b1b9.
=> build_image: disable verity again for 1192

oem/generic/check_etag.sh
Curl and CloudFlare now support HTTP/2. While that's great news, it breaks `fix_check_etag.sh` because headers are lower-case in h2.
Forcing HTTP/1.0 has good backwards compatibility with Curl, no significant performance impact and resolves the inconsistency.
=> Force HTTP/1.0 in fix_check_etag.sh

build_library/oem_aci_util.sh, build_library/vm_image_util.sh, build_oem_aci, image_to_vm.sh
This adds a function to the `image_to_vm` library that builds an ACI file and installs it into `/usr/share/oem`.  The "building" part is a new library file that reuses the `create_prod_image` function, run in a slightly more controlled environment.
This is for coreos/bugs#1468.
=> Add OEM ACI building support

build_image
Depends on https://github.com/coreos/coreos-overlay/pull/2242
=> build_image: re-enable verity by default

build_library/parallels_pvs.sh, build_library/vm_image_util.sh, build_library/write_hdd.sh
Two new image types have been added:
1. parallels - this produces VM images with extension pvm.tgz that can be loaded directly into Parallels Desktop
2. vagrant_parallels - this produces a Vagrant box that works with parallels vagrant provider (http://parallels.github.io/vagrant-parallels/)
Just like vmdk and others we rely on qemu-img to convert raw images. Support for Parallels disk images was added to qemu-img in version 2.4.
I had to do a slight refactoring to add a concept of a VM_LAYOUT to support Parallels. Just like a disk layout, a vm layout defines how the VM is organized. Parallels Desktop requires a specific directory structure for its configuration and also for the disks. It not as simple as vmware vmx + vmdk side-by-side.
I also removed the box files from the actual image …
=> add support for Parallels Desktop VM images

build_jobs/02_sdk.sh, build_jobs/02_toolchains.sh, build_jobs/03_packages.sh, build_jobs/04_images.sh, build_jobs/05_vm.sh, build_jobs/stub.sh
The chroot update/creation step must live in Jenkins but after that the
jobs can use these scripts. A template is provided in stub.sh
=> build_jobs: split minimal prefix out of job scripts

build_jobs/03_packages.sh, build_jobs/04_images.sh, build_jobs/05_vm.sh
Not applicable to these scripts which do not build branches other than
their own. Plus the 1010 branch is dead now anyway.
=> build_jobs: drop old hack for 1010 branch

build_library/vm_image_util.sh
this stops qemu-img info from choking on vpc-type images made with our
patched qemu.
=> build_library: pass force_size when converting disks to vpc

build_library/grub.cfg
By default, ACPI is disabled on arm64 even if support is built in to the kernel (```CONFIG_ACPI=y```).
This change adds a new grub.cnf variable ```platform_options``` and sets ```acpi=force``` to enable ACPI on arm64 platforms.
Needs https://github.com/coreos/coreos-overlay/pull/2273 (arm64_defconfig: Enable ACPI).
=> grub.cfg: Enable arm64 ACPI

build_library/check_root
Make detecting issues like coreos/bugs#1139 easier.
=> check_root: make #!/usr/bin/env a special case

build_image
Technically it's "one of dev, prod, or container". I think this makes that slightly clearer. (edit: actually, multiple are okay too!)
=> build_image: specify arguments more clearly

build_library/set_lsb_release
Fixes https://github.com/coreos/bugs/issues/1751.
=> set_lsb_release: properly quote lsb-release

build_library/check_root
Treating documentation files as not really having dependencies is normal among other distros.  By ignoring script headers in documentation files, we'll drop a few of our own warnings.
=> check_root: ignore scripts in documentation

build_library/disk_layout.json, build_library/disk_util
I've left file system labels off everything except ROOT, OEM, EFI-SYSTEM, and config-2.
This fixes coreos/bugs#1628.
=> disk_util: differentiate between partition and FS labels

build_library/build_image_util.sh
They're not in the root fs, but they are in the initramfs.  Handle this by augmenting the package list with packages that are both
- build dependencies of coreos-kernel, and
- configured to cause rebuilds of coreos-kernel when their sub-slot changes.
=> build_image: Include {ignition,bootengine} in {packages,licenses}.txt

build_image, build_library/build_image_util.sh
Tested with amd64 coreos_production_qemu_uefi and did not see any regressions.
Depends on:
https://github.com/coreos/grub/pull/42 "Add arm64 verity support" 
coreos/coreos-overlay#2277 "coreos-sources: Add arm64 verity hash"
cc: @mjg59
=> scripts: Add arm64 verity support

build_library/template_vmware.ovf
Without setting ovf:transport attribute to com.vmware.guestInfo in the VirtualHardwareSection, coreos-cloudinit returns empty values. VM Hardware version 7.
=> Set ovf transport mode so guestinfo gets available to coreos-cloudinit

build_library/vm_image_util.sh
Allow `coreos-install -o vmware_raw` to install Container Linux with the vmware OEM.
Use base DISK_LAYOUT to reduce the minimum disk size.
Fixes coreos/bugs#359.
=> image_to_vm: Add vmware_raw image type

build_library/build_image_util.sh, build_library/grub_install.sh, build_library/prod_image_util.sh
On arm64, extract only GRUB, since there is no shim.  On dev builds, extract neither.
Tested with:
- amd64 dev
- amd64 prod
- arm64 prod
- amd64 prod official
=> build_image: Extract and upload GRUB/shim EFI images for signing

build_library/build_image_util.sh
Fixes up missing bit from e630a36e50799ec72305b03a6d6fe354d2b8b059.
cc: @dm0-
=> build_image: Correctly disable verity on unsupported boards

offline_signing/download.sh, offline_signing/sign.sh
I haven't tested the signing part yet.  Consider this a proposal until then.
=> Add Secure Boot to the offline signing process

build_library/toolchain_util.sh
This appears to fix the toolchain bootstrapping failure where `/usr/bin/$CHOST-g++` is not installed when building without a pre-existing catalyst directory.
=> toolchain: always run gcc-config

build_library/check_root, build_library/test_image_content.sh
Inspired by https://github.com/coreos/bugs/issues/1807
This is not sufficient to actually catch that one since it was a tempfiles created symlink, and so only broke at runtime. I'll write a short kola test too.
This is a nice way to let developers know early for certain other breakages hopefully though.
cc @bgilbert
=> check_root: add check for broken symlinks

offline_signing/download.sh, offline_signing/sign.sh
This reverts #640 since Secure Boot will not be added to this beta, and it will be annoying having the wrong download URL etc. when it is time to sign updates.
=> Revert Secure Boot for the beta branch

offline_signing/download.sh, offline_signing/sign.sh
Apply #649 to master.  We'll revisit when Secure Boot is ready.
=> Revert Secure Boot signing changes

build_docker_aci, build_library/build_image_util.sh, build_library/ebuild_aci_manifest.in, build_library/ebuild_aci_util.sh
Testing done:
I've built, signed (with my personal key), and hosted the output of `./build_docker_aci 1.12.6` at https://storage.googleapis.com/users.developer.core-os.net/euank/skim/...
Next steps are adding upload/sign utilities, improving version number related to that probably, and making it work for more than just 1.12.6
Using the ignition config below, it works:
<details>
```yaml
systemd:
units:
- name: docker.service
contents: |-
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=docker.socket
Requires=docker.socket
[Service]
Type=simple
EnvironmentFile=-/run/flannel/flannel_docker_opts.env
EnvironmentFile=-/etc/coreos/docker.conf
Environment=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/bin
ExecStartPre=/usr/bin/rkt …
```
=> Initial docker-aci build thing

build_library/dev_image_util.sh, build_library/prod_image_util.sh
We've always generated these license manifests (detailing which ebuilds
are covered by which license), but never published them. This adds these
manifests to the list of published files so that they are publicly
available.
=> build_library: upload image licenses

build_library/set_lsb_release
os-release is requested in bug reports, and knowing which board
the problem occurred on is often helpful.
=> os-release: Add COREOS_BOARD variable

build_library/build_image_util.sh, build_library/generate_grub_hashes.py, build_library/grub.cfg
Detect first boot based on the existence of a `coreos/first_boot` file in the EFI partition, and set `coreos.first_boot=detected` command line argument when found. We use `detected` rather than `1` so the initramfs knows that it should [mount the ESP and delete the file](https://github.com/coreos/bootengine/pull/107). This lets us defer clearing the first-boot flag until Ignition has run successfully, without having to change the disk GUID after filesystems are mounted.
Continue detecting the first-boot disk GUID and adding the command-line argument to randomize it, since we still want unique disk GUIDs regardless of Ignition.
=> Set coreos.first_boot based on existence of file in ESP

build_library/catalyst.sh, update_chroot
This is the reverse of #657 for beta.  If the existing SDK or Jenkins workspace was building alpha/master with the new Perl, ensure the downgrade can succeed (at least with `--nousepkg`).
=> Handle Perl downgrades

build_library/release_util.sh
This is a work in progress.  There is an issue with `emerge` commands failing unless `PORTAGE_SSH_OPTS=` is set in the environment.  The was this is set up, it only works with the SDK scripts since the `FETCHCOMMAND_GS` and `RESUMECOMMAND_GS` variables are not in the user's login environment.
=> Sign uploaded binary packages

tag_release
I'd like to have some degree of cryptographic source verification for our OS builds.  It's easy enough to sign the development build tags while they're created automatically, but the manually tagged releases will need to be handled at the `tag_release` point since that tag is built directly.  We can supply the list of public keys of taggers to Jenkins to verify them.
We should all have a GPG key associated with our primary coreos.com e-mail address and be using that address for Git authorship information, so this change should be transparent to everyone that runs the script (aside from maybe a `pinentry` prompt).
=> Require signed release tags

tag_release
Backport #663 for tagging with a beta branch checkout.
=> Sign beta release tags

tag_release
Backport #663 for tagging with an alpha branch checkout.  (This one is pessimistic in that it will only matter if we have some security vulnerability before next week and have to rebuild 1367.)
=> Sign alpha release tags

tag_release
Backport #663 for tagging with a stable branch checkout.
=> Sign stable release tags

common.sh
https://github.com/coreos/scripts/pull/647 started exporting COREOS_BUILD_ID whenever it was found in version.txt, even if its value was blank. Because COREOS_BUILD_ID is in ENVIRONMENT_WHITELIST, this caused generated build IDs to be propagated into the SDK chroot environment and reused for every build in a `cork enter` session. Stop exporting COREOS_BUILD_ID when we set it ourselves.
See also #550.
=> common: Don't export COREOS_BUILD_ID

build_library/build_image_util.sh
Jenkins uses separate chroots for package and image builds, so $BUILD_DIR may not have the relevant packages installed.  This was causing bootengine, ignition, and gcc not to show up in packages.txt, and licenses.txt to be nearly empty.
=> build_image_util: Don't query the $BUILD_DIR vdb

build_library/build_image_util.sh, build_library/dev_image_util.sh, build_library/ebuild_aci_util.sh, build_library/oem_aci_util.sh, build_library/prod_image_util.sh
This changes the format from:
sys-apps/systemd-212-r8::coreos GPL-2 LGPL-2.1 MIT public-domain
to a JSON structure:
```json
[
{
"project": "sys-apps/systemd-212-r8::coreos",
"license": ["GPL-2", "LGPL-2.1", "MIT", "public-domain"]
}
]
```
We don't have to worry about the changing format because the previous
format was never published. This is designed to match the
bill-of-materials [1] format so that it can be consumed by the site.
[1]: https://github.com/coreos/license-bill-of-materials
=> build_library: reformat the license file as json

build_library/set_lsb_release
See https://github.com/coreos/coreos-overlay/pull/2463 for the
reasoning.
This was missed in that sweep of changes.
cc @crawford
=> lsb_release: update BUG_REPORT_URL

build_library/check_root
I'm not sure if the `x86_32` entry makes sense, but the `go` lines have it, so it's included.
=> check_root: silence the incorrect libperl warnings

build_library/dev_image_util.sh
When building dev images, the `PORTAGE_BINHOST` value during build time is written to the image's `make.conf`.  This breaks the default binary package setup, since Jenkins is using `gs://` URLs for signed package verification and authenticated downloads, and the `make.conf` doesn't inherit the `GS_*` variables to handle those schemes.
This should be reverted when signed packages are properly supported by default in the dev images.
=> build_image: do not use gs:// URLs in dev images

build_library/template_vmware.ovf
When OVA template is not being used, the default dhcp value yes will
trigger cloud-init to generate a 00-.network file, which will break
network connectivity Intermittently. Please see the details here:
https://github.com/coreos/bugs/issues/1802#issuecomment-297847614
=> Change default value of dhcp for vmware template to no

tag_release
Now when an alpha is tagged (i.e. it branches off `master.xml`), the manifest repository still gets a tag, a commit on master, and a new build branch pointing at that commit, but by default an additional commit is appended to the build branch that branches the projects `coreos-overlay`, `portage-stable`, and `scripts` in the manifest.  When given the `--push` option, a build branch is created in each of these project repositories so everything is prepared for future minor releases to build upon.
This is implemented in yet another option so that the previous behavior is still available, but it probably makes sense to just hard-code the default behavior of `--branch` and `--branch_projects` and drop those options.
=> tag_release: branch important projects automatically for alpha tags

sdk_lib/enter_chroot.sh
We were chowning the host directory, not the one in the chroot.
Host gpg &ge; 2.1.13 puts the gpg-agent socket in `/run/user/UID/gnupg`, which is bind-mounted into the chroot, but the SDK gpg was ignoring it because `/run/user/UID` was not owned by `UID`. This broke tag signing with YubiKeys.
=> enter_chroot: Fix ownership of /run/user/UID

build_library/catalyst.sh, update_chroot
Since 1353 (with the last old Perl SDK) rotates out of stable next week, drop the Perl SDK workarounds.
I am going to throw this at Jenkins first, but there should be no problem with merging it before 1353 is retired.  The workarounds would only matter if we needed to build a new 1353 release before Monday, but even then, an alternate workaround is to just delete all Jenkins workspaces after a 1353 build.
=> Revert Perl workarounds

offline_signing/download.sh
A validation for the channel variable was also added so old users of the
3-argument form would get a sensical error if they used a invocation
from their history.
Just a small quality-of-life thing.
=> offline_signing: take download channel as an arg

build_library/vm_image_util.sh
These commits set the oem package for virtualbox to "virtualbox" and vagrant to "vagrant-virtualbox". Depends on https://github.com/coreos/coreos-overlay/pull/2602 and https://github.com/coreos/coreos-overlay/pull/2603
=> Use new oem packages for virtualbox and vagrant

build_library/dev_image_util.sh, build_library/vm_image_util.sh, setup_board
See https://github.com/coreos/coreos-overlay/pull/2610 for `BOARD_USE`.
=> Drop ISO/PXE support for amd64-generic, and an unused variable

build_library/vm_image_util.sh
This reverts the vagrant image back to using oem-vagrant because we
don't want to break the existing images. It moves the new,
Ignition-powered virtualbox flavor of vagrant into a new image.
=> build_library: split vagrant and vagrant vbox

update_chroot
This changes the workaround from supporting upgrading Perl 5.20 to 5.22, to supporting downgrading from 5.24 to 5.22.
Part of coreos/portage-stable#556.
=> Transition beta to handle Perl 5.24

update_chroot
This changes the workaround from supporting upgrading Perl 5.20 to 5.22, to supporting downgrading from 5.24 to 5.22.
Part of coreos/portage-stable#556.
=> Transition stable to handle Perl 5.24

build_library/check_root, update_chroot
This is #657 again for upgrading 5.22 to 5.24.
Part of coreos/portage-stable#556.
=> Add workarounds for upgrading to Perl 5.24

update_chroot
This adds the workaround supporting downgrading from 5.24 to 5.22.
Part of coreos/portage-stable#556.
=> Transition alpha to handle Perl 5.24

tag_release
Some releases may omit the SDK for expediency.
=> tag_release: Verify SDK version exists

core_sign_update, offline_signing/sign.sh
This replaces #630
See the additional commits for changes made.
This has been lightly tested by re-signing a previous release and getting an update payload with the same hash.
cc @crawford @dm0-
=> coreos_sign_update: Use smartcards for signing (updated)

core_sign_update
=> core_sign_update: fix flag parsing for keys_separator

update_chroot
This is to run test builds for Jenkins SDKs downgrading to releases without Python 3.
=> Support dropping Python 3 in alpha

update_ebuilds
And default to git instead of rsync.
git has no rate limiting and will generally be quicker after the first
run.
This does leave a bit of extra data in your local portage-stable `.git`
directory, but it doesn't seem unreasonable to me.
Note: this means we lose the "ChangeLog" file. In the rsync
repositories, that file has been generated by egencache, but the git
repository never has it checked in.
cc @dm0-
=> update_ebuilds: replace cvs with git

build_library/vm_image_util.sh
Depends on: 
https://github.com/coreos/portage-stable/pull/566 (bump(dev-lang/nasm): sync with upstream)
https://github.com/coreos/coreos-overlay/pull/2665 (sys-firmware/edk2: New package)
=> vm_image_util: Update to use edk2 package

build_library/qemu_template.sh
I used a condensed indentation in the `case` statements to avoid the `set` commands from wrapping so much.  I can change it to match what was there before if you like.
=> build_library: Update qemu script to run on arm64 machines

update_chroot
This reverts commit 6508cf3faaef0643e6ece9124048591c7435de4f.
All update channels are now using Perl 5.24, so workarounds are no longer required.
=> Revert "update_chroot: fix SDK updates during the Perl 5.24 upgrade"

update_chroot
This reverts commit 6508cf3faaef0643e6ece9124048591c7435de4f.
All update channels are now using Perl 5.24, so workarounds are no longer required.
=> Revert "update_chroot: fix SDK updates during the Perl 5.24 upgrade" in alpha

update_chroot
This reverts commit 6508cf3faaef0643e6ece9124048591c7435de4f.
All update channels are now using Perl 5.24, so workarounds are no longer required.
=> Revert "update_chroot: fix SDK updates during the Perl 5.24 upgrade" in beta

build_torcx_store
For https://github.com/coreos/bugs/issues/1930.
=> build_torcx_store: hold back Docker to 1.12 for 1492

build_torcx_store
Add `--quiet` so build_torcx_store doesn't flood the terminal.
=> build_torcx_store: emerge quietly

build_torcx_store
Part of coreos/coreos-overlay#2718.
=> build_torcx_store: Bump the Docker image to 17.06

update_chroot
This seems to fix the ccache permission issues `update_chroot` hits
while building ninja.
cc @dm0-
=> update_chroot: set a CCACHE_UMASK

build_library/vm_image_util.sh
Reserve the unsuffixed name for a raw image, in case we ever want to support installing to disk using `coreos-install -o` on a PXE-booted system.
=> build_library: rename oracle_oci image to oracle_oci_qcow

build_image, build_library/build_image_util.sh, build_library/release_util.sh, build_library/torcx_manifest.sh, build_torcx_store, jenkins/images.sh, jenkins/packages.sh
=> rework torcx uploading to include a manifest

build_image, build_library/build_image_util.sh, build_library/release_util.sh, build_library/torcx_manifest.sh, build_torcx_store, jenkins/images.sh, jenkins/packages.sh
This backports https://github.com/coreos/scripts/pull/737
We'll want to pull in https://github.com/euank/scripts/commit/e858e727b05668da98ebb74878c298097cf2a03b once this branch goes to beta as well.
=> Backport build_torcx_store manifest changes

build_torcx_store
=> build_torcx_store: default to docker 1.12 for 1520

build_library/build_image_util.sh, build_library/torcx_manifest.sh
This includes the source package of all torcx packages that are installed on disk, including cases where multiple versions of the same package are available.
=> build_library: Add torcx source packages to the package list

build_library/torcx_manifest.sh
This avoids odd "null" lines appearing in torcx image names.
=> build_library: Filter out null paths in torcx manifests

build_library/vm_image_util.sh
Now that we're shipping multiple docker packages in the image, 1 GiB is not enough to boot successfully.
=> vm_image_util: bump PXE and ISO scripts to 2 GiB RAM

build_library/check_root
This will silence some warnings when we actually install a Rust project.
=> check_root: Ignore missing Rust libraries

jenkins/formats-amd64-usr.txt
Part of https://github.com/coreos/bugs/issues/2035#issuecomment-331966047
cc @bgilbert
=> jenkins/formats-amd64: add oracle_oci_qcow

build_torcx_store
This updates the default image to 17.09 and adds an optional 17.03 image for Kubernetes 1.8.
Part of coreos/coreos-overlay#2797.
=> Update Docker torcx images

build_torcx_store
Backports #759
Depends on coreos/coreos-overlay#2798
This still builds 1.12 as the optional on-disk version in case we have to build an alpha point release.  The versions still need to be swapped during promotion.
=> Update Docker to 17.09 and add 17.03 in alpha

build_torcx_store
=> build_torcx_store: Set Docker 1.12 as the default image

build_library/toolchain_util.sh, update_chroot
This omits the toolchain packages' version-pinning flag for the binutils package while it is being upgraded.  It also removes older versions installed in parallel that cause unwanted rebuilds.
When stable has the upgraded version, this can be reverted.
Part of coreos/portage-stable#586.
=> update_chroot: Avoid a portage crash while upgrading binutils

build_library/test_image_content.sh
Part of coreos/portage-stable#590
=> build_library: Whitelist the Go 1.9 GLSA

build_library/dev_image_util.sh
We already hardcode similar urls a bit below (the sync-uri).
Not hardcoding the binhost results in an incorrect value during
embargoed build uploads.
=> dev_image_util: hardcode correct portage binhost

build_torcx_store
Part of coreos/coreos-overlay#2851
=> build_torcx_store: Upgrade to Docker 17.10 on disk

build_library/build_image_util.sh, build_library/modify_image_util.sh, build_library/prod_image_util.sh
It's useful to have this information available without starting an image or digging up a binpkg.
=> build_library: upload kernel config as release artifact

build_library/disk_util
`mkfs.vfat` was defaulting to FAT16 based on the size of the partition. The UEFI spec (2.7 errata A, section 13.3) implies that only FAT32 is necessarily supported on the ESP, and we've received a report of hardware that doesn't recognize FAT16.
Addresses https://github.com/coreos/bugs/issues/2246.
=> disk_util: use FAT32 on ESP

build_torcx_store
Prepare alpha for beta promotion.
=> build_torcx_store: Make the LTS Docker CE version the default

build_library/disk_util
This reverts commit 7f058d61a10384ca81c88245c4ff80c08f89ad6b.
Reverting because of bug 2284 [1] where grub will sometimes fail due to
memory corruption. This is _not_ the cause of the bug, and the bug can
even be reproduced with this reversion, but it seems to occur less when
not using fat32.
[1] https://github.com/coreos/bugs/issues/2284
=> Revert "disk_util: use FAT32 on ESP"

build_image, build_library/modify_image_util.sh, image_to_vm.sh, jenkins/vm.sh
Make prod images default instead of dev images. Additionally, clean up some of the flag logic around the --dev_image flag in image_to_vm.sh
This should probably wait until after 1632.0.0 because it will almost certainly break some jenkins jobs.
Edit: waiting until after 1646.0.0
@bgilbert
=> *: make prod images default

build_torcx_store
Part of coreos/coreos-overlay#2973.
=> build_torcx_store: Upgrade the default Docker to 17.12

build_torcx_store
The default version is updated from 17.12 to 18.01, and the LTS version is updated from 17.09 to 17.12.
Part of coreos/coreos-overlay#3005
=> build_torcx_store: Update Docker's default and LTS images

build_torcx_store
In preparation for the beta channel, we'd normally set the default Docker image to the LTS version and drop the extra edge version.  Since branching, the alpha's default 17.12 image has become the LTS version, so just drop the extra 17.09 image for consistency.
=> build_torcx_store: Drop the Docker 17.09 image

tag_release
1632.2.0 -> 1632.2.1 was being rejected.
=> tag_release: fix version validation when bumping patch on branch

build_torcx_store
Part of coreos/coreos-overlay#3057
=> build_torcx_store: Upgrade the default Docker to 18.02

update_chroot
Part of coreos/coreos-overlay#3059
=> update_chroot: Drop obsolete GCC versions, older than 7.3.0

build_library/catalyst.sh
It provides no value when it works, and it's randomly causing failures to build toolchains due to permissions problems after certain releases.  This also requires taking it out of FEATURES in the portage profile (which is the SDK profile by default).
Test Jenkins runs of SDK and toolchains jobs both ran in the same time as with ccache enabled.
=> catalyst: Disable ccache

build_library/qemu_template.sh
Fix a bug in the qemu template, which is used for generating `coreos_production_qemu.sh` or similar. Setting `$VM_CDROM` in the qemu script does not work as expected when installing Container Linux from the given bootable CDROM image. That's probably because qemu-system-x86_64 expects another boot option `-boot order=d` to be able to boot from the given CDROM drive. Let's specify a `-boot` as well as `-drive` option for the given CDROM drive.
=> Fix a bug when setting VM_CDROM in qemu template

build_torcx_store
Part of coreos/coreos-overlay#3143
=> build_torcx_store: Bump the default Docker version to 18.03

build_library/toolchain_util.sh, sdk_lib/enter_chroot.sh, update_chroot
This addresses errors when entering the SDK.
Part of coreos/coreos-overlay#3161
=> enter_chroot: Drop special locale-gen handling

build_torcx_store
Part of coreos/coreos-overlay#3172
=> build_torcx_store: Bump the default to 18.04 and LTS to 18.03

build_library/disk_util
FAT32 seemed to aggravate https://github.com/coreos/bugs/issues/2284, but now that that issue has been addressed, we can return to the correct filesystem type.
This reverts #779 and fixes coreos/bugs#2246.
=> Revert "Revert "disk_util: use FAT32 on ESP""

build_library/test_image_content.sh
Part of coreos/portage-stable#657
=> build_library: Whitelist the new Go 1.10 GLSA

build_torcx_store
We'll continue to build Docker 18.03 as the default since it's the current LTS version.  For consistency with other non-alpha releases, drop the unused extra image (the previous LTS 17.12).
=> Drop Docker 17.12 for beta promotion

build_library/grub.cfg
This allows booting the default entry even if GRUB authentication is configured in `/usr/share/oem/grub.cfg`.
Fixes https://github.com/coreos/bugs/issues/1597.
=> build_library: add --unrestricted to default GRUB menuentry

offline_signing/transfer.sh
This pr changes the update percent setting to use the new `group percent` `updateservicectl` command, and creates a new `transfer.sh` command call `roll` (the old `roll` is renamed to `ready`) which creates a linear rollout that reaches 100% in the provided number of seconds for each channel. `roll` only sets up a rollout for the amd64 application (the arm64 application is just set to 100% by default, so there is no need for a rollout).
The old `roll` command, now called `ready`, sets the update percent for amd64 to 0% (and arm64 to 100%) and updates the channel to point at the provided package version. 
This is the only place in the scripts repo that needs to be updated for the new version of updateservicectl. It relies on the new version of updateservicectl to be in the sdk, and also …
=> transfer.sh: changes to updateservicectl usage for roller rollout strategies

build_library/catalyst.sh
We now have an SDK with Python 3.6, so this isn't needed.
Part of coreos/coreos-overlay#3310
=> Revert "catalyst: Temporarily disable update_seed"

jenkins/images.sh, jenkins/packages.sh, jenkins/sdk.sh, jenkins/toolchains.sh, jenkins/vm.sh
Builds are broken by coreos/mantle@93f52c5a692e3f5ee8984a75373ded6b87307432.
Backports #820
=> Drop Jenkins --experimental for beta

jenkins/images.sh, jenkins/packages.sh, jenkins/sdk.sh, jenkins/toolchains.sh, jenkins/vm.sh
Builds are broken by coreos/mantle@93f52c5a692e3f5ee8984a75373ded6b87307432.
Backports #820
=> Drop Jenkins --experimental for stable

build_torcx_store
Switch to LTS Docker as the default
Part of coreos/coreos-overlay#3336
=> Prepare 1828 for beta promotion

build_torcx_store
Part of coreos/coreos-overlay#3335
=> build_torcx_store: Bump the default Docker to 18.06

build_torcx_store
Part of coreos/coreos-overlay#3343
=> build_torcx_store: Stop building the old LTS image

build_torcx_store
Part of coreos/coreos-overlay#3395
=> Revert Docker 18.06 to 18.03 in beta

build_torcx_store
Part of coreos/coreos-overlay#3401
=> Revert "build_torcx_store: Revert Docker 18.06 to 18.03"

signing/sign.sh
We use gpg --enarmor to convert the torcx manifest binary sigs to ascii
armored ones. Unfortunately --enarmor just wraps the binary blob without
realizing its a signature which breaks torcx. Pipe the output through
sed to fix the header.
=> signing/sign.sh: fix armoring

signing/sign.sh
We use gpg --enarmor to convert the torcx manifest binary sigs to ascii
armored ones. Unfortunately --enarmor just wraps the binary blob without
realizing its a signature, which breaks torcx. Pipe the output through
sed to fix the header.
=> backport "signing/sign.sh: fix armoring" to alpha

signing/sign.sh
We use gpg --enarmor to convert the torcx manifest binary sigs to ascii
armored ones. Unfortunately --enarmor just wraps the binary blob without
realizing its a signature, which breaks torcx. Pipe the output through
sed to fix the header.
=> backport "signing/sign.sh: fix armoring" to beta

signing/sign.sh
We use gpg --enarmor to convert the torcx manifest binary sigs to ascii
armored ones. Unfortunately --enarmor just wraps the binary blob without
realizing its a signature, which breaks torcx. Pipe the output through
sed to fix the header.
=> backport "signing/sign.sh: fix armoring" to stable

build_library/test_image_content.sh
Part of coreos/portage-stable#697
=> build_library: Whitelist the systemd GLSA until we have 239

signing/transfer.sh
Both subcommands take a `SIGDIR` argument which is assumed to be within a git repo we can safely sync.  `devsign` creates commits but does not (currently) push them, leaving that to the user.
=> transfer.sh: add subcommands to devsign and sign releases

build_library/test_image_content.sh
We could just whitelist `201812-09` like the others here, but Go is no longer built for the boards since coreos/coreos-overlay#3523, so there are no vulnerable versions found by the GLSA check.
=> build_library: Drop whitelisted Go GLSAs

build_library/catalyst.sh, build_library/check_root
The Perl update will break SDK bootstrapping during seed update, so disable it again.  This can be reverted after bumping the SDK to a version that includes the new Perl.
Part of coreos/portage-stable#710
=> catalyst: Temporarily disable update_seed again

build_library/catalyst.sh
This reverts commit 7d99b4dbddf9d4bd0ae9777e41d0fac82067c6f6.
Requires coreos/manifest#160
=> Revert "catalyst: Temporarily disable update_seed again"

build_library/disk_util
When loop device partition nodes aren't cleaned up, building images will fail with:
mkfs.vfat: Partitions or virtual mappings on device '/dev/loop0', not making filesystem (use -I to override)
Just add the flag unconditionally to work around it.
=> disk_util: Add -I for mkfs.vfat

build_library/disk_util
Backport https://github.com/coreos/scripts/pull/864.
=> disk_util: Add -I for mkfs.vfat for 1967

build_library/test_image_content.sh
This no longer matches since upgrading to 241.
=> build_library: Drop whitelisted systemd GLSA

build_library/disk_layout.json
Builds are beginning to run out of space with 3GB. Bump to 4GB.
=> disk_layout: bump dev container from 3 to 4GB

jenkins/packages.sh, jenkins/sdk.sh, jenkins/toolchains.sh
This should make it safer for scheduling multiple runs on small workers without running out of disk space due to multiple workspaces having duplicate SDKs.
=> jenkins: Free more disk space on successful job completion

build_library/toolchain_util.sh
Portage crashes trying to build the binutils security update.  This can be applied to produce a new SDK and toolchains binpkgs then reverted.
Part of coreos/portage-stable#738
=> build_library: Add temporary workaround for binutils update

build_library/toolchain_util.sh
=> Revert "build_library: Add temporary workaround for binutils update"

setup_board
Add a workaround to be sure we're using the correct binutils when SDK
sharing.
=> setup_board: add workaround for binutils issue

setup_board
Add a workaround to be sure we're using the correct binutils when SDK
sharing. In this case we want the old binutils, not the new one.
=> setup_board: add workaround for binutils issue [build-2219]

setup_board
Add a workaround to be sure we're using the correct binutils when SDK
sharing. In this case we want the old binutils, not the new one.
=> setup_board: add workaround for binutils issue [build-2191]

build_library/test_image_content.sh
Both CVE fixes were backported.
Part of https://github.com/coreos/portage-stable/pull/742.
=> test_image_content: whitelist polkit GLSA

build_library/test_image_content.sh
Backported the dbus GLSA.  Ignoring the Perl one.
Part of https://github.com/coreos/coreos-overlay/pull/3761.
=> test_image_content: whitelist Perl and dbus GLSAs

build_library/test_image_content.sh
It only affects a default-disabled USE flag, and our overlay ebuild is too old to even support it.
Part of https://github.com/coreos/coreos-overlay/pull/3803.
=> test_image_content: whitelist OpenSSH GLSA

build_library/disk_util
This fails frequently but should succeed if retried. This should reduce
failed builds.
=> disk_util: retry loopback mounts if they fail

build_library/disk_util
This fails frequently but should succeed if retried. This should reduce failed builds.
=> disk_util: retry loopback mounts if they fail on 2303

build_library/test_image_content.sh
systemd and sudo are already fixed.  Git was fixed by updating to 2.23.2, not 2.24.1.  Samba is 2 years old and customized, thus difficult to update.  file, Python, and gdb are only in the SDK.
Part of https://github.com/coreos/portage-stable/pull/750.
=> test_image_content: whitelist some GLSAs
